### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hoyleb** [JohannesBuchner/APEMoST#1]
Dear Johannes,
Thanks for this excellent code, and the python wrappers.

I'm having some installation troubles. I'm on a mac [v10.9.3] and have macports up to date, through which I've gsl.

I clone this repo, then try and run
%>make all
gcc -I src -O3 -std=c99 -fopenmp -fPIC -Wall -Werror -Wextra -ansi -pedantic  -DWITHOUT_GARBAGE_COLLECTOR   -c -o src/mcmc_parser.o src/mcmc_parser.c
clang: error: argument unused during compilation: '-fopenmp
make: **\* [src/mcmc_parser.o] Error 1

So I remove the -fopenmp flag and
%>make all

gcc -I src -O3 -std=c99  -fPIC -Wall -Werror -Wextra -ansi -pedantic  -DWITHOUT_GARBAGE_COLLECTOR   -c -o src/mcmc_parser.o src/mcmc_parser.c
src/mcmc_parser.c:37:12: error: static declaration of 'strnlen' follows non-static declaration
static int strnlen(char \* s, int maxlen) {
/usr/include/string.h:133:10: note: previous declaration is here
size_t   strnlen(const char _, size_t) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
1 error generated.
make: *_\* [src/mcmc_parser.o] Error 1

Am I doing something obvious and wrong? If so, would you mind telling me how I'm messing up?

Warm regards,

Ben.

**Comment by JohannesBuchner** [comment]
Interesting, you are compiling with clang, not gcc, it seems. I have not tried that.
You can remove the "-Werror" flag in the Makefile.
It seems your compiler has strnlen already defined, so you can remove that function in src/mcmc_parser.c . 
Hope that helps.

**Comment by hoyleb** [comment]
Thanks Johannes,
This fixed it.
I also had to change my default gcc link to that given by macports (which had openmp libraries) so that Clang wasn't being used.

Thanks again,
Cheers,

Ben.
